### ISSUE TITLE
Cannot build ruby 3.0.0 on Fedora 36

### ISSUE THREAD

**Issue by kostyanf14** [rvm/rvm#5216]
## Description

Cannot build ruby 3.0.0 on Fedora 36

## Steps to reproduce

1. Install `rvm` on Fedora 36.
2. Try to install ruby version 3.0.0 (`rvm install 3.0.0`)

## Expected behavior

It compiles and installs.

## Actual behavior

Compilation failed

```
Searching for binary rubies, this might take some time.
No binary rubies available for: fedora/36/x86_64/ruby-3.0.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for fedora.
Requirements installation successful.
Installing Ruby from source to: /home/user/.rvm/rubies/ruby-3.0.0, this may take a while depending on your cpu(s)...
ruby-3.0.0 - #downloading ruby-3.0.0, this may take a while depending on your connection...
ruby-3.0.0 - #extracting ruby-3.0.0 to /home/user/.rvm/src/ruby-3.0.0.....
ruby-3.0.0 - #configuring.........................................................................
ruby-3.0.0 - #post-configuration..
ruby-3.0.0 - #compiling......................................................................................................|
Error running '__rvm_make -j2',
please read /home/user/.rvm/log/1652452060_ruby-3.0.0/make.log

There has been an error while running make. Halting the installation.
```

* [configure.log and make.log](https://gist.github.com/kostyanf14/509b113b79e38cd2a0f814edeb840d7a)

make.log contains the next error: `ossl_pkey_rsa.c:885:58: error: ‘RSA_SSLV23_PADDING’ undeclared (first use in this function); did you mean ‘RSA_NO_PADDING’?`

## Environment info

```
system:

  system:
    uname:        "Linux vm 5.17.5-300.fc36.x86_64 #1 SMP PREEMPT Thu Apr 28 15:51:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Fedora"
    version:      "36"
    architecture: "x86_64"
    bash:         "/usr/bin/bash => GNU bash, version 5.1.16(1)-release (x86_64-redhat-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "fedora/36/x86_64"

  rvm:
    version:      "1.29.12 (latest)"
    updated:      "2 hours 31 minutes 30 seconds ago"
    path:         "/home/user/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         ""
    irb:          ""
    gem:          ""
    rake:         ""

  environment:
    PATH:         "/home/user/.local/bin:/home/user/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/user/.rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""
```

## Additional info

Look like an issue similar to https://github.com/rvm/rvm/issues/5209. Fedora 36 uses openssl3 (`openssl-1:3.0.2-5.fc36.x86_64`)

**Comment by sergiouve** [comment]
Same here with ruby version `2.6.6`. I was able to install it with the solution provided here: https://github.com/rvm/rvm/issues/5209#issuecomment-1114159447 but afterwards `bundle install` and other commands fails with:
```bash
Could not verify the SSL certificate for https://gems.contribsys.com/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile
sources and change 'https' to 'http'.
```

I tried changing the sources to `http` and still does not work, looks like the `openssl` from `$HOME/.rvm/usr` cannot access my local SSL certificates.

**Comment by gizmo87898** [comment]
I can reproduce this on a brand new install of Fedora 36 w/ rvm & ruby-3.0.0, but i dont even get anything in my log file :/

**Comment by sebastianwebber** [comment]
Similar issues in a brand new fedora 36 installation - using x86_64.

**Comment by jmbuscemi** [comment]
I have the same issue as https://github.com/rvm/rvm/issues/5216#issuecomment-1128810621 - I'm on a fresh Fedora 36 install with ruby 2.7.1. Using https://github.com/rvm/rvm/issues/5209#issuecomment-1114159447 got me able to install ruby 2.7.1, but now `bundle install` fails.

**Comment by YuanLiou** [comment]
I've face this problem on my Fedora 36 desktop, too.

This instruction come from https://github.com/rvm/rvm/issues/5209#issuecomment-1186893261
solved my problems.

```bash
$rvm pkg install openssl
$rvm install ruby-<version> --with-openssl-dir=/usr/share/rvm/usr
```

If you faced the `__rvm_make install`, you can do this:

```bash
$rvmsudo rvm get head
```

To upgrade your rvm install.

**Comment by conathan** [comment]
RHEL/AlmaLinux/RockyLinux 9, have patches to compile Ruby 3.0 with the system OpenSSL 3.0,  (Error above is OpenSSL no longer defines RSA_SSLV23_PADDING).

https://git.centos.org/rpms/ruby/blob/c9/f/SOURCES

Saying that, I personally haven't tried making this work with their patches.



Recently did my own variant though, of just removing SSLV23_padding reference, and disable gcc treating deprecations as errors,  (I do not know if this is the proper solution or not), but compiles on ruby 2.5.9.  Ruby 3.0 I believe has additional changes though to not compile on OpenSSL 3.0 so believe this will need additional tweaks  (For our environment, wanted changes as minimal as possible (so not worrying about using deprecated OpenSSL 3.0 code).

[ruby-2.5.9-opensslv30-1.patch.txt](https://github.com/rvm/rvm/files/9437701/ruby-2.5.9-opensslv30-1.patch.txt)

**Comment by zak905** [comment]
I had the same issue on a brand new Fedora 38 installation. After reading https://github.com/rvm/rvm/issues/5209#issuecomment-1114159447, I installed ruby 3.1.4 which installed without openssl issues. 
```
rvm get head
rvm install ruby 3.1.4
```

**Comment by shawndwells** [comment]
> I had the same issue on a brand new Fedora 38 installation. After reading [#5209 (comment)](https://github.com/rvm/rvm/issues/5209#issuecomment-1114159447), I installed ruby 3.1.4 which installed without openssl issues.
> 
> ```
> rvm get head
> rvm install ruby 3.1.4
> ```

Also doing a fresh install of Fedora 38 and encountering these errors.

```Error running '__rvm_make -j1',```

tail of the log
````ossl_pkey_rsa.c: In function ‘Init_ossl_rsa’:
ossl_pkey_rsa.c:885:58: error: ‘RSA_SSLV23_PADDING’ undeclared (first use in this function); did you mean ‘RSA_NO_PADDING’?
  885 | #define DefRSAConst(x) rb_define_const(cRSA, #x, INT2NUM(RSA_##x))
      |                                                          ^~~~
ossl_pkey_rsa.c:950:5: note: in expansion of macro ‘DefRSAConst’
  950 |     DefRSAConst(SSLV23_PADDING);
      |     ^~~~~~~~~~~
ossl_pkey_rsa.c:885:58: note: each undeclared identifier is reported only once for each function it appears in
  885 | #define DefRSAConst(x) rb_define_const(cRSA, #x, INT2NUM(RSA_##x))
      |                                                          ^~~~
ossl_pkey_rsa.c:950:5: note: in expansion of macro ‘DefRSAConst’
  950 |     DefRSAConst(SSLV23_PADDING);
      |     ^~~~~~~~~~~
At top level:
cc1: note: unrecognized command-line option ‘-Wno-self-assign’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-parentheses-equality’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-constant-logical-operand’ may have been intended to silence earlier diagnostics
make[2]: *** [Makefile:328: ossl_pkey_rsa.o] Error 1
make[2]: Leaving directory '/home/parallels/.rvm/src/ruby-3.0.0/ext/openssl'
make[1]: *** [exts.mk:260: ext/openssl/all] Error 2
make[1]: Leaving directory '/home/parallels/.rvm/src/ruby-3.0.0'
make: *** [uncommon.mk:300: build-ext] Error 2
++ /scripts/functions/support : __rvm_make()  383 > return 2
````

**Comment by zak905** [comment]
@shawndwells based on the logs, it seems like you are installing ruby-3.0.0. As mentionned https://github.com/rvm/rvm/issues/5209#issuecomment-1114159447, versions equal or superior to 3.1 have worked around the openssl issue properly.
