### ISSUE TITLE
After update to 1.29.9 rvm erroring on OpenSSL

### ISSUE THREAD

**Issue by DaveSanders** [rvm/rvm#4818]
## Description

Note: if there is some way for me to install an older version of rvm, I'd really like to try that, because I'm currently unable to develop now. About to switch to some other version manager if I can't resolve this quickly.

Received a notice that I was behind on rvm.  Did an upgrade to 1.29.9. Now, rubies installed are missing OpenSSL, and there are errors during ruby installation during the "importing gemset" section:

```
.r/l/1/gem.install.gem-wrappers->=1.4.0.log
  1 ERROR:  Loading command: install (LoadError)
  2         cannot load such file -- openssl
  3 ERROR:  While executing gem ... (NoMethodError)
  4     undefined method `invoke_with_build_args' for nil:NilClass
```

After a ruby install, a bundle install gives me:

```
Could not load OpenSSL.
You must recompile Ruby with OpenSSL support or change the sources in your Gemfile from 'https' to 'http'.
Instructions for compiling with OpenSSL using RVM are available at http://rvm.io/packages/openssl.
```

Brew has openssl@1.1 installed, and I cannot remove or link that because it is the "system openssl".  `which openssl` returns /usr/bin/openssl

## Steps to reproduce

I upgraded rvm first, found the error, got flummoxed and then uninstalled and reinstalled both rvm AND brew.  Tried both released and master rvm (next).

I also tried installing ruby like so:
```
rvm reinstall 2.3.7 --with-openssl-dir=`brew --prefix openssl`
```
but still had the error.

## Expected behavior

Expect ruby to be compiled with OpenSSL

## Actual behavior

It does not install OpenSSL and openssl related commands fail.

## Environment info

Mac Catalina v10.15.1
Brew v2.1.16
rvm 1.29.9 and 1.29.9-next

ruby-2.3.7:

  system:
    uname:        "Darwin Samwise.local 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.15"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)"
    zsh:          "/usr/local/bin/zsh => zsh 5.7.1 (x86_64-apple-darwin19.0.0)"
    remote_path:  "osx/10.15/x86_64"
    xcode:        "11.2.1"

  rvm:
    version:      "1.29.9-next (master)"
    updated:      "10 minutes 58 seconds ago"
    path:         "/Users/dave/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.3.7p456"
    date:         "2018-03-28"
    platform:     "x86_64-darwin19"
    patchlevel:   "2018-03-28 revision 63024"
    full_version: "ruby 2.3.7p456 (2018-03-28 revision 63024) [x86_64-darwin19]"

  homes:
    gem:          "/Users/dave/.rvm/gems/ruby-2.3.7"
    ruby:         "/Users/dave/.rvm/rubies/ruby-2.3.7"

  binaries:
    ruby:         "/Users/dave/.rvm/rubies/ruby-2.3.7/bin/ruby"
    irb:          "/Users/dave/.rvm/rubies/ruby-2.3.7/bin/irb"
    gem:          "/Users/dave/.rvm/rubies/ruby-2.3.7/bin/gem"
    rake:         "/Users/dave/.rvm/rubies/ruby-2.3.7/bin/rake"

  environment:
    PATH:         "/Users/dave/.rvm/gems/ruby-2.3.7/bin:/Users/dave/.rvm/gems/ruby-2.3.7@global/bin:/Users/dave/.rvm/rubies/ruby-2.3.7/bin:/Users/dave/.rvm/bin:/usr/local/sbin:/Users/dave/.nvm/versions/node/v12.4.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Users/dave/.fzf/bin"
    GEM_HOME:     "/Users/dave/.rvm/gems/ruby-2.3.7"
    GEM_PATH:     "/Users/dave/.rvm/gems/ruby-2.3.7:/Users/dave/.rvm/gems/ruby-2.3.7@global"
    MY_RUBY_HOME: "/Users/dave/.rvm/rubies/ruby-2.3.7"
    IRBRC:        "/Users/dave/.rvm/rubies/ruby-2.3.7/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

**Comment by DaveSanders** [comment]
After sleeping on it, and consultation with another developer, I realized that this is happening due to the old version of ruby that the project is using.  Because 2.3 is end of life, that's not really RVM's problem. It's my own and this project's need to move forward.

I'm attempting to move it to ruby 2.6.5 now, and hoping that everything works ok. But for now, while it would be great to have a workaround, I'm guessing the only way to deal with this situation is to spin up a Linux VM or container to work on the project.

Time marches on...

**Comment by pkuczynski** [comment]
Yeah, the issue is that brew does not offer old openssl I think, hence you need to upgrade ruby.
