### ISSUE TITLE
failed to install ruby 2.3.0 on OS X 10.11.6

### ISSUE THREAD

**Issue by RookieZn** [rvm/rvm#3744]
It was OK when I installed ruby 2.2.0, but not work on ruby 2.3.0
```shell
Error running '__rvm_make -j 1',
showing last 15 lines of /Users/Rookie/.rvm/log/1472865655_ruby-2.3.0/make.log
compiling ./missing/explicit_bzero.c
compiling ./missing/setproctitle.c
compiling dmyenc.c
linking miniruby
config.status: creating ruby-runner.c
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/Rookie/.rvm/src/ruby-2.3.0/./miniruby (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/Rookie/.rvm/src/ruby-2.3.0/./miniruby (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

make: *** [.rbconfig.time] Trace/BPT trap: 5
+__rvm_make:0> return 2
There has been an error while running make. Halting the installation.
```
And `/usr/lib/libSystem.B.dylib` exists

Thanks for any help

**Comment by RookieZn** [comment]
The mistake results from updating xcode 8 beta on OSX 10.11.
Run `xcode-select --install` in terminal could fix it.

**Comment by gurix** [comment]
happens to me as well and as @RookieZn suggested, ´xcode-select --install´ fixed the problem, but I had to reinstall the affected gem. In my case eventmachine. 👍

**Comment by Pradeep123g** [comment]
Below error occurs to me. I have OS X El Capitan, version 10.11.6 and Xcode full package is installed and its version is 6.4

On entering 'rails s' on the command line.

Thin web server (v1.6.4 codename Gob Bluth)
Maximum connections set to 1024
Listening on 0.0.0.0:5045, CTRL+C to stop
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/pg2233/.rvm/gems/ruby-2.1.2/extensions/x86_64-darwin-13/2.1.0-static/eventmachine-1.0.8/rubyeventmachine.bundle (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/pg2233/.rvm/gems/ruby-2.1.2/extensions/x86_64-darwin-13/2.1.0-static/eventmachine-1.0.8/rubyeventmachine.bundle (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5




As suggested I already tried 'xcode-select --install' but I get the error "Can't install the software because it is not currently available from the Software Update server."

Got the same error when I had installed Xcode 8 from App store.

Kindly help me out, any suggestions

Thanks.

**Comment by RookieZn** [comment]
@Pradeep123g Would you like to post your output when running 'xcode-select -p' ? I guess something wrong with the active developer directory. Try 'xcode-select -r' first to see if it helps.
I've never encountered this error so I can only guess. Good luck.

**Comment by Pradeep123g** [comment]
@RookieZn Thanks for the response. Sure, below is the output when I ran  'xcode-select -p' 

/Applications/Xcode.app/Contents/Developer

**Comment by Pradeep123g** [comment]
@RookieZn Also I ran 'sudo xcode-select -r' and did not get any error

**Comment by RookieZn** [comment]
@Pradeep123g Then 'xcode-select --install' works or not ?

**Comment by Pradeep123g** [comment]
@RookieZn I did. But the same error as I said before for 'xcode-select --install'. 

"Can't install the software because it is not currently available from the Software Update server."

**Comment by rajesh-zuu** [comment]
Pradeep123g  Did u get the solution as I am facing same problem yet I am using rbenv for versioning instead rvm :)

**Comment by Pradeep123g** [comment]
@rajesh-zuu No luck so far, still facing the problem.

**Comment by Pradeep123g** [comment]
@RookieZn My issue is resolved. I was using rvm so all I did was to start from zero by installing rvm and then ruby again and proceed from there.

**Comment by RookieZn** [comment]
@Pradeep123g Cheers!

**Comment by CodeWithPassionKeepLearning** [comment]
I ran into the same issue while installing Ruby. ´xcode-select --install´ worked for me! @RookieZn thanks for the fix!

**Comment by davidhamann** [comment]
@rajesh-zuu Had the same problem as you with rbenv. `xcode-select --install`, then re-install of rbenv, then again the ruby install worked.

**Comment by constdrop** [comment]
I had same issue. 'xcode-select --install' worked on my OSX El Captain and fix it.

**Comment by adam** [comment]
Just encountered this installing ruby 2.4.0. Resolution was successful, however I did have to `rvm reinstall ruby-2.4.0` in order to resolve a gemset creation issue where the original run of the rvm install process had halted.

**Comment by sudiptosen** [comment]
Damn! it worked after and ONLY after 'xcode-select --install' 
Then repeated the steps to reinstall rbenv from [HERE](https://gorails.com/setup/osx/10.12-sierra)

**Comment by javieramp** [comment]
`xcode-select --install` Works!

**Comment by AndrejHyben** [comment]
xcode-select --install Works too
