### ISSUE TITLE
ree - /usr/include/tk.h:78:11: fatal error: 'X11/Xlib.h' file not found

### ISSUE THREAD

**Issue by josh-m-sharpe** [rvm/rvm#2352]
ree fails to build on mavericks and rvm 1.23.14

trace here:
https://gist.github.com/crankharder/f2dcec8f87cc79412a99
