### ISSUE TITLE
Patch Ruby 1.8.7 to compile against openssl 1.1.0

### ISSUE THREAD

**Issue by conathan** [rvm/rvm#5164]
## Description

Attempting to install ruby 1.8.7 does not work on OSX brew w/ openssl 1.1.x or Ubuntu w/ openssl 1.1.x.

## Steps to reproduce

(Linux)
<pre>
rvm ruby-1.8.7-p374 do gem install bundler -v 1.17.3
</pre>

(OSX)
<pre>
LDFLAGS="-L/usr/local/opt/openssl@1.1/lib" \
CPPFLAGS="-I/usr/local/opt/openssl@1.1/include -Wno-implicit-function-declaration" \
PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig" \
rvm install ruby-1.8.7-p374 --rubygems 1.3.7 --patches ~/.rvm/patches/ruby-1.8.7-p374-openssl11x-1.patch
rvm ruby-1.8.7-p374 do gem install bundler -v 1.17.3
</pre>

## Expected behavior

Install of ruby-1.8.7-p374 - #complete 

## Actual behavior

Error running '__rvm_make -j1',
please read /usr/local/rvm/log/1638492268_ruby-1.8.7-p374/make.log
(Multiple errors, openssl based, expected, posting one example)
ossl_digest.c:84:38: error: ‘EVP_MD_CTX_destroy’ undeclared (first use in this function); did you mean ‘EVP_MD_CTX_reset’?

## Environment info

root@xubuntu2004:~# rvm info

ruby-3.0.0:

  system:
    uname:        "Linux xubuntu2004 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Ubuntu"
    version:      "20.04"
    architecture: "x86_64"
    bash:         "/usr/bin/bash => GNU bash, version 5.0.16(1)-release (x86_64-pc-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "ubuntu/20.04/x86_64"

  rvm:
    version:      "1.29.12 (latest)"
    updated:      "1 hour 3 minutes 58 seconds ago"
    path:         "/usr/local/rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "3.0.0p0"
    date:         "2020-12-25"
    platform:     "x86_64-linux"
    patchlevel:   "2020-12-25 revision 95aff21468"
    full_version: "ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]"

  homes:
    gem:          "/usr/local/rvm/gems/ruby-3.0.0"
    ruby:         "/usr/local/rvm/rubies/ruby-3.0.0"

  binaries:
    ruby:         "/usr/local/rvm/rubies/ruby-3.0.0/bin/ruby"
    irb:          "/usr/local/rvm/rubies/ruby-3.0.0/bin/irb"
    gem:          "/usr/local/rvm/rubies/ruby-3.0.0/bin/gem"
    rake:         "/usr/local/rvm/rubies/ruby-3.0.0/bin/rake"

  environment:
    PATH:         "/usr/local/rvm/gems/ruby-3.0.0/bin:/usr/local/rvm/gems/ruby-3.0.0@global/bin:/usr/local/rvm/rubies/ruby-3.0.0/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
    GEM_HOME:     "/usr/local/rvm/gems/ruby-3.0.0"
    GEM_PATH:     "/usr/local/rvm/gems/ruby-3.0.0:/usr/local/rvm/gems/ruby-3.0.0@global"
    MY_RUBY_HOME: "/usr/local/rvm/rubies/ruby-3.0.0"
    IRBRC:        "/usr/local/rvm/rubies/ruby-3.0.0/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

## Provided Patch

Attached is a patch (applied via --patches ~/.rvm/patches/ruby-1.8.7-p374-openssl11x-1.patch) that will allow ruby 1.8.7 to compile against openssl 1.1.x.  This is mostly backported from ruby 2.4.0

[ruby-1.8.7-p374-openssl11x-1.patch.txt](https://github.com/rvm/rvm/files/7645996/ruby-1.8.7-p374-openssl11x-1.patch.txt)

**Comment by pacificalabs** [comment]
I have been fixing an old MERB app running Ruby 1.87 & your patch script has saved a huge amount of time. thank you!

**Comment by conathan** [comment]
We have a couple inhouse software builds, one still on Ruby 1.8.7 and another one on Ruby 2.0.  I wasn't expecting RVM to pick up the patches, but thought wouldn't hurt to pass them along (They did, so merged upstream, so works a bit more out of the box if you use their development version).  Thought in case there's problems with it, others could point them out.

AlmaLinux 9 environment for where we use these,  and developers on OSx.  Took longer then I like to make them, and personally don't like such big diff's, but seems to be working fine so far (shrug).
