### ISSUE TITLE
`rvm <version> do blah` says GEM_HOME/GEM_PATH not set

### ISSUE THREAD

**Issue by ElvenSpellmaker** [rvm/rvm#4802]
## Description

`rvm <version> do blah` doesn't seem to set-up the environment for the chosen Ruby when running a command, instead saying that the GEM_HOME/GEM_PATH aren't set.

However the commands seem to run correctly, it's annoying to have the message polluting the build log for each step.

I can't use `rvm use 2.4.1` and then run my command as I'm on a build server which is non-interactive and so `rvm is not a function`.

I can't reproduce this issue interactively and so I'm finding this really hard to debug. I also can't reproduce this on TeamCity, which uses the same puppet module to install rvm.

Also, if I source in rvm via `source /usr/local/rvm/scripts/rvm` then the error is emitted while it sets up the environment which means I can't avoid the problem by sourcing before each VSTS Step.

## Steps to reproduce

Run a non-interactive VSTS build using `rvm 2.4.1 do bundle exec rake syntax`

## Expected behavior

No warning message.

## Actual behavior

```
Warning: PATH set to RVM ruby but GEM_HOME and/or GEM_PATH not set, see:
    https://github.com/rvm/rvm/issues/3212
```

## Environment info

CentOS 7 running VSTS agent in a build
`rvm` installed as root and used by `vsoagent` user
