### ISSUE TITLE
Ruby 2.3.x and older are not compatible with OpenSSL 1.1.x on Kali

### ISSUE THREAD

**Issue by itsmeroy2012** [rvm/rvm#3958]
## Description:-

Failing to install ruby 2.3.3

## Steps to reproduce:-

On running the commands:-

 1. curl -L https://get.rvm.io | bash -s stable
 2. curl -o rvm.sh -L https://get.rvm.io
 3. cat rvm.sh | bash -s stable
 4. rvm --install $(cat .ruby-version)
 5. On running  'uname -v'
          #1 SMP Debian 4.6.4-1kali1 (2016-07-21)

 
 I also ran rvm get master as suggested and still the errors persisted.

## ERROR: -
leolanders@kali:~/metasploit-framework$ rvm --install $(cat .ruby-version)
ruby-2.3.3 is not installed - installing.
ruby-2.3.3 - #removing src/ruby-2.3.3..
Searching for binary rubies, this might take some time.
No binary rubies available for: debian/Kali_Linux_Rolling/x86_64/ruby-2.3.3.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for debian.
Installing requirements for debian.
Updating system..leolanders password required for 'apt-get --quiet --yes update': 
..
Installing required packages: libreadline6-dev.........
Requirements installation successful.
Installing Ruby from source to: /home/leolanders/.rvm/rubies/ruby-2.3.3, this may take a while depending on your cpu(s)...
ruby-2.3.3 - #downloading ruby-2.3.3, this may take a while depending on your connection...
ruby-2.3.3 - #extracting ruby-2.3.3 to /home/leolanders/.rvm/src/ruby-2.3.3....
ruby-2.3.3 - #configuring..........................................................
ruby-2.3.3 - #post-configuration..
ruby-2.3.3 - #compiling............................................................................
Error running '__rvm_make -j4',
showing last 15 lines of /home/leolanders/.rvm/log/1489597153_ruby-2.3.3/make.log
exts.mk:210: recipe for target 'ext/openssl/all' failed
make[1]: *** [ext/openssl/all] Error 2
make[1]: *** Waiting for unfinished jobs....
compiling objspace.c
compiling object_tracing.c
linking shared-object objspace.so
make[2]: Leaving directory '/home/leolanders/.rvm/src/ruby-2.3.3/ext/objspace'
linking shared-object date_core.so
make[2]: Leaving directory '/home/leolanders/.rvm/src/ruby-2.3.3/ext/date'
linking shared-object nkf.so
make[2]: Leaving directory '/home/leolanders/.rvm/src/ruby-2.3.3/ext/nkf'
make[1]: Leaving directory '/home/leolanders/.rvm/src/ruby-2.3.3'
uncommon.mk:203: recipe for target 'build-ext' failed
make: *** [build-ext] Error 2
++ return 2
There has been an error while running make. Halting the installation.
Using /home/leolanders/.rvm/gems/ruby-2.3.3
Warning! Executable 'ruby' missing, something went wrong with this ruby installation!
Warning! Executable 'gem' missing, something went wrong with this ruby installation!
Warning! Executable 'irb' missing, something went wrong with this ruby installation!

**Comment by pkuczynski** [comment]
Could you please gist `/home/leolanders/.rvm/log/1489597153_ruby-2.3.3/make.log`?

**Comment by itsmeroy2012** [comment]
[one.txt](https://github.com/rvm/rvm/files/850479/one.txt)

**Comment by pkuczynski** [comment]
Could you please run and post here `rvm info` and also check if you have `libssl1.0-dev` or `libssl-dev` installed? It seems that you are running on Kali linux, which we do not have support yet. Which version of Kali linux are you running? Do you know which version of Debian it is based on?

**Comment by itsmeroy2012** [comment]
#Command:-

sudo apt-get -y install   libssl-dev libssl1.0-dev

#Gives: -

Reading package lists... Done
Building dependency tree       
Reading state information... Done
libssl-dev is already the newest version (1.1.0e-1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libssl1.0-dev : Conflicts: libssl-dev but 1.1.0e-1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by itsmeroy2012** [comment]
**leolanders@kali:~$ cat /etc/issue**
Kali GNU/Linux Rolling \n \l
**leolanders@kali:~$ uname -v**
#1 SMP Debian 4.6.4-1kali1 (2016-07-21)
**leolanders@kali:~$ lsb_release -a**
No LSB modules are available.
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling

**Comment by canrosss** [comment]
amd facing a similar problem.. 

compiling ossl_digest.c
In file included from ossl.h:58:0,
                 from ossl_digest.c:11:
/usr/include/openssl/asn1_mac.h:10:2: error: #error "This file is obsolete; please update your software."
 #error "This file is obsolete; please update your software."
  ^~~~~

**Comment by pkuczynski** [comment]
@itsmeroy2012 and @canrosss could you please post output of following commands:

```
cat /etc/lsb-release
dpkg --print-architecture
```

**Comment by canrosss** [comment]
Hi this its my output. Thanks

cat /etc/lsb-release
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"

dpkg --print-architecture
amd64

**Comment by itsmeroy2012** [comment]
root@kali:~# cat /etc/lsb-release
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"
root@kali:~# 
root@kali:~# dpkg --print-architecture
amd64

**Comment by mpapis** [comment]
does `ruby-2.4.1` install?

**Comment by mrpalacios** [comment]
Hello,
2.4.1 seems to install ok, here is my output:

%> cat /etc/lsb-release
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"

%> dpkg --print-architecture
amd64

%> rvm info

ruby-2.4.1:
[...]
  rvm:
    version:      "rvm 1.29.1 (master) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]"
    updated:      "1 hour 45 minutes 8 seconds ago"
    path:         "/usr/local/rvm"
    autolibs:     "[0] Limit RVM automation as much as possible."

  ruby:
    interpreter:  "ruby"
    version:      "2.4.1p111"
    date:         "2017-03-22"
    platform:     "x86_64-linux"
    patchlevel:   "2017-03-22 revision 58053"
    full_version: "ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]"
[...]

On the other hand, I am having trouble to install 2.1.5 that is specified in a package's Gemfile, with same error:
/usr/include/openssl/asn1_mac.h:10:2: error: #error "This file is obsolete; please update your software."
 #error "This file is obsolete; please update your software."

%> apt-get -y install libssl-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libssl-dev is already the newest version (1.1.0e-1).
0 upgraded, 0 newly installed, 0 to remove and 156 not upgraded.

**Comment by bermannoah** [comment]
Also confirming: I've been able to get 2.4 and higher to install. It seems like the problem is specific to 2.3.3.

**Comment by mpapis** [comment]
fixing this might require back porting patches from ruby

**Comment by TheZoq2** [comment]
I had the same issue on arch when installing 2.3.3. The workaround described at the bottom of this page worked for me.

https://wiki.archlinux.org/index.php/RVM

```
$ rvm pkg install openssl
$ rvm remove 2.3.3
$ rvm install 2.3.3 -C --with-openssl-dir=$HOME/.rvm/usr
```

**Comment by youngd24** [comment]
I am having the same issue trying to install the BeEF framework on Kali 2.0 with updates current as of today. The BeEF installer script here, https://raw.githubusercontent.com/beefproject/beef/master/install-beef, runs this line to install rvm:

curl -Lsk https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer | bash

I attempted the most recent suggestion of:

$ rvm pkg install openssl
$ rvm remove 2.3.3
$ rvm install 2.3.3 -C --with-openssl-dir=$HOME/.rvm/usr

That errors out on the last step with the following, which is the same error produced by the BeEF installer script command:

Error running '__rvm_make -j2',
please read /usr/local/rvm/log/1493786264_ruby-2.3.3/make.log
There has been an error while running make. Halting the installation.

The last 45 lines of the make.log have the same error as previously mentioned:
make[2]: Entering directory '/usr/local/rvm/src/ruby-2.3.3/ext/openssl'
compiling ossl_x509ext.c
In file included from ossl.h:57:0,
                 from ossl_x509ext.c:10:
/usr/include/openssl/asn1_mac.h:10:2: error: #error "This file is obsolete; please update your software."
 #error "This file is obsolete; please update your software."
  ^~~~~
In file included from ossl.h:222:0,
                 from ossl_x509ext.c:10:
openssl_missing.h:78:35: error: macro "EVP_MD_CTX_create" passed 1 arguments, but takes just 0
 EVP_MD_CTX *EVP_MD_CTX_create(void);
                                   ^
In file included from /usr/include/openssl/x509.h:23:0,
                 from /usr/include/openssl/x509v3.h:14,
                 from ossl.h:58,
                 from ossl_x509ext.c:10:
openssl_missing.h:82:6: error: expected declaration specifiers or ‘...’ before ‘(’ token
 void EVP_MD_CTX_init(EVP_MD_CTX *ctx);
      ^
openssl_missing.h:90:6: error: expected declaration specifiers or ‘...’ before ‘(’ token
 void EVP_MD_CTX_destroy(EVP_MD_CTX *ctx);
      ^
ossl_x509ext.c: In function ‘ossl_x509ext_get_value’:
ossl_x509ext.c:405:2: warning: implicit declaration of function ‘M_ASN1_OCTET_STRING_print’ [-Wimplicit-function-declaration]
  M_ASN1_OCTET_STRING_print(out, ext->value);
  ^~~~~~~~~~~~~~~~~~~~~~~~~
ossl_x509ext.c:405:36: error: dereferencing pointer to incomplete type ‘X509_EXTENSION {aka struct X509_extension_st}’
  M_ASN1_OCTET_STRING_print(out, ext->value);
                                    ^~
Makefile:301: recipe for target 'ossl_x509ext.o' failed
make[2]: *** [ossl_x509ext.o] Error 1
make[2]: Leaving directory '/usr/local/rvm/src/ruby-2.3.3/ext/openssl'
exts.mk:210: recipe for target 'ext/openssl/all' failed
make[1]: *** [ext/openssl/all] Error 2
make[1]: *** Waiting for unfinished jobs....
installing default nkf libraries
linking shared-object nkf.so
make[2]: Leaving directory '/usr/local/rvm/src/ruby-2.3.3/ext/nkf'
make[1]: Leaving directory '/usr/local/rvm/src/ruby-2.3.3'
uncommon.mk:203: recipe for target 'build-ext' failed
make: *** [build-ext] Error 2
++ return 2

Other info:
root@kali:/opt# cat /etc/lsb-release 
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"

OpenSSL packages installed:
root@kali:/opt# dpkg-query -l | grep openssl
ii  libcrypt-openssl-bignum-perl                                     0.07-2                               amd64        Perl module to access OpenSSL multiprecision integer arithmetic libraries
ii  libcrypt-openssl-rsa-perl                                        0.28-5                               amd64        module for RSA encryption using OpenSSL
ii  libcurl4-openssl-dev:amd64                                       7.52.1-5                             amd64        development files and documentation for libcurl (OpenSSL flavour)
ii  libevent-openssl-2.0-5:amd64                                     2.0.21-stable-3                      amd64        Asynchronous event notification library (openssl)
ii  openssl                                                          1.1.0e-1                             amd64        Secure Sockets Layer toolkit - cryptographic utility
ii  perl-openssl-defaults:amd64                                      3                                    amd64        version compatibility baseline for Perl OpenSSL packages
ii  python-openssl                                                   16.2.0-1                             all          Python 2 wrapper around the OpenSSL library

**Comment by krionical** [comment]
@TheZoq2 I second this solution for arch linux. Some sort of ssl problem and complaints of the file being obsolete were resolved with this work around.

**Comment by pkuczynski** [comment]
@mpapis backporting a patch would not be possible as old versions or Ruby are not compatible with OpenSSL 1.1

**Comment by pkuczynski** [comment]
I prepared a patch and added a full support for Kali. This should solve the issue with OpenSSL too.
@krionical, @youngd24, @TheZoq2, @bermannoah, @mrpalacios, @itsmeroy2012, @canrosss could you please try following:

```
rvm get branch /bugfix/3958-kali
rvm install 2.3.3
rvm install 2.3.4 # OR
```

If it fails, please gist logs and output.

**Comment by pkuczynski** [comment]
Anybody having a minute to test it please?

**Comment by youngd24** [comment]
Sure, I have a little time, what do you need done?

**Comment by youngd24** [comment]
Sure, what would you like done?

**Comment by youngd24** [comment]
Sure, I have a few, what do you need done?

**Comment by pkuczynski** [comment]
Run following commands and if they fail, post the output:

```
rvm get branch /bugfix/3958-kali
rvm install 2.3.3
```

**Comment by renpic** [comment]
It is working, thanks a lot!

**Comment by itsmeroy2012** [comment]
It works !! Thanks alot, sorry for being inactive, I got caught up with life  @pkuczynski

**Comment by ccakgunduz** [comment]
I'm tring to install ruby 2.3.0 on Kali Rolling (4.9.30-1kali1)
However /bugfix/3958-kali is not reachable anymore. What should I do?

**Comment by pkuczynski** [comment]
`rvm get master`

**Comment by ccakgunduz** [comment]
Lame on me. Thanks!

**Comment by r3b00t5** [comment]
`rvm get master`  doesn't seem to resolve the issue on my host. I still can't reach the bugfix.

```
`Downloading https://github.com/rvm/rvm/archive/bugfix/3958-kali.tar.gz
curl: (22) The requested URL returned error: 404 Not Found

Could not download 'https://github.com/rvm/rvm/archive/bugfix/3958-kali.tar.gz'.
  curl returned status '22'.

Downloading https://bitbucket.org/mpapis/rvm/get/bugfix/3958-kali.tar.gz
curl: (22) The requested URL returned error: 404 

Could not download 'https://bitbucket.org/mpapis/rvm/get/bugfix/3958-kali.tar.gz'.
  curl returned status '22'.
```

**Comment by mathieujobin** [comment]
I'm curious why does this needs a separate patch for Ubuntu and Kali and other distrib ?

shouldn't `rvm get head` on any distrib gets me going?

**Comment by mathieujobin** [comment]
i see

**Comment by maddoctor87** [comment]
after this 
rvm get branch /bugfix/3958-kali


gpg: Signature made dom 27 ago 2017 23:08:32 CEST
gpg:                using RSA key E206C29FBF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [sconosciuto]
gpg:                 aka "Michal Papis <michal.papis@toptal.com>" [sconosciuto]
gpg:                 aka "[jpeg image of size 5015]" [sconosciuto]
gpg: ATTENZIONE: questa chiave non è certificata con una firma fidata!
gpg:          Non ci sono indicazioni che la firma appartenga al proprietario.
Impronta digitale della chiave primaria: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
    Impronta digitale della subchiave: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/usr/local/rvm/archives/rvm-installer'
Downloading https://github.com/rvm/rvm/archive/bugfix/3958-kali.tar.gz
curl: (22) The requested URL returned error: 404 Not Found

Could not download 'https://github.com/rvm/rvm/archive/bugfix/3958-kali.tar.gz'.
  curl returned status '22'.

Downloading https://bitbucket.org/mpapis/rvm/get/bugfix/3958-kali.tar.gz
curl: (22) The requested URL returned error: 404 

Could not download 'https://bitbucket.org/mpapis/rvm/get/bugfix/3958-kali.tar.gz'.
  curl returned status '22'.

**Comment by mpapis** [comment]
@maddoctor87 this branch is already merged to master, run `rvm get master` instead

**Comment by maddoctor87** [comment]
dpkg-query -l | grep openssl
ii  libevent-openssl-2.1-6:amd64              2.1.8-stable-4                       amd64        Asynchronous event notification library (openssl)
ii  openssl                                   1.1.0f-5                             amd64        Secure Sockets Layer toolkit - cryptographic utility
ii  perl-openssl-defaults:amd64               3                                    amd64        version compatibility baseline for Perl OpenSSL packages
ii  python-openssl                            16.2.0-1                             all          Python 2 wrapper around the OpenSSL library


DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"


amd 64

i did 
rvm get master

same eror
Error running '__rvm_make -j4'
plese help

**Comment by mpapis** [comment]
@maddoctor87 please open a new ticket - including all the outputs (follow the instructions in ticket template)

**Comment by flored27** [comment]
I also have trouble with this same error, and have tried both rvm get master and bug fix 3958

**Comment by pkuczynski** [comment]
@maddoctor87 and @flored27 please open a new issue providing all necessary listed in the issue template (logs, system info, etc).

**Comment by celesteking** [comment]
This is bullshit. What about Gentoo?

**Comment by xofred** [comment]
```shell
rvm reinstall 2.3.4 -C --with-openssl-dir=$HOME/.rvm/usr
```
Works for me on mac catalina 10.15.3 with brew installed openssl. Thanks @TheZoq2 !
