### ISSUE TITLE
ruby-2.3.3 doesn't compile on Debian 8.3

### ISSUE THREAD

**Issue by coldnebo** [rvm/rvm#4000]
## Description

Trying to compile 2.3.3 fails on Debian 8.

## Steps to reproduce

    $ rvm install 2.3.3 --disable-binary

## Expected behavior

success!

## Actual behavior

```
$ rvm install 2.3.3 --disable-binary
ruby-2.3.3 - #removing src/ruby-2.3.3..
Checking requirements for debian.
Requirements installation successful.
Installing Ruby from source to: /DONOTDELETE/shared/rvm/rubies/ruby-2.3.3, this may take a while depending on your cpu(s)...
ruby-2.3.3 - #downloading ruby-2.3.3, this may take a while depending on your connection...
ruby-2.3.3 - #extracting ruby-2.3.3 to /DONOTDELETE/shared/rvm/src/ruby-2.3.3....
ruby-2.3.3 - #configuring..........................................................
ruby-2.3.3 - #post-configuration..
ruby-2.3.3 - #compiling.......
Error running '__rvm_make -j4',
showing last 15 lines of /DONOTDELETE/shared/rvm/log/1493051631_ruby-2.3.3/make.log
compiling parse.c
compiling process.c
compiling random.c
In file included from /usr/include/x86_64-linux-gnu/sys/syscall.h:31:0,
                 from /usr/include/syscall.h:1,
                 from random.c:81:
random.c: In function ‘fill_random_bytes_syscall’:
random.c:541:16: error: ‘__NR_getrandom’ undeclared (first use in this function)
  ret = syscall(SYS_getrandom, seed, size, flags);
                ^
random.c:541:16: note: each undeclared identifier is reported only once for each function it appears in
Makefile:375: recipe for target 'random.o' failed
make: *** [random.o] Error 1
make: *** Waiting for unfinished jobs....
++ return 2
There has been an error while running make. Halting the installation.
```

## Environment info

```
$ lsb_release -a
LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.3 (jessie)
Release:	8.3
Codename:	jessie
```

```
$ dpkg -l *libc6*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                          Version                     Architecture                Description
+++-=============================================-===========================-===========================-================================================================================================
ii  libc6:amd64                                   2.19-18+deb8u7.tmw3         amd64                       GNU C Library: Shared libraries
ii  libc6:i386                                    2.19-18+deb8u7.tmw3         i386                        GNU C Library: Shared libraries
un  libc6-amd64                                   <none>                      <none>                      (no description available)
ii  libc6-dbg:amd64                               2.19-18+deb8u7.tmw3         amd64                       GNU C Library: detached debugging symbols
ii  libc6-dev:amd64                               2.19-18+deb8u7.tmw3         amd64                       GNU C Library: Development Libraries and Header Files
ii  libc6-dev-i386                                2.19-18+deb8u7.tmw3         amd64                       GNU C Library: 32-bit development libraries for AMD64
ii  libc6-dev-x32                                 2.19-18+deb8u7.tmw3         amd64                       GNU C Library: X32 ABI Development Libraries for AMD64
ii  libc6-i386                                    2.19-18+deb8u7.tmw3         amd64                       GNU C Library: 32-bit shared libraries for AMD64
un  libc6-i686                                    <none>                      <none>                      (no description available)
ii  libc6-x32                                     2.19-18+deb8u7.tmw3         amd64                       GNU C Library: X32 ABI Shared libraries for AMD64
un  libc6.1                                       <none>                      <none>                      (no description available)
un  libc6.1-dev                                   <none>                      <none>                      (no description available)
```

**Comment by jrgifford** [comment]
That's odd. I just pulled down a new debian 8 docker container to test against:
```
root@5c4c869b8ced:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.7 (jessie)
Release:        8.7
Codename:       jessie
```

```
root@5c4c869b8ced:~# dpkg -l *libc6*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                                           Version                              Architecture                         Description
+++-==============================================================-====================================-====================================-=================================================================================================================================
ii  libc6:amd64                                                    2.19-18+deb8u7                       amd64                                GNU C Library: Shared libraries
un  libc6-amd64                                                    <none>                               <none>                               (no description available)
ii  libc6-dev:amd64                                                2.19-18+deb8u7                       amd64                                GNU C Library: Development Libraries and Header Files
un  libc6.1                                                        <none>                               <none>                               (no description available)
un  libc6.1-dev                                                    <none>                               <none>                               (no description available)
```

```
root@5c4c869b8ced:~# rvm install 2.3.3 --disable-binary
Checking requirements for debian.
Installing requirements for debian.
Updating system..
Installing required packages: patch, bzip2, gawk, libssl-dev, make, libc6-dev, patch, zlib1g-dev, libyaml-dev, libsqlite3-dev, sqlite3, autoconf, libgmp-dev, libgdbm-dev, libncurses5-dev, automake, libtool, bison, pkg-config, libffi-dev, libgmp-dev, libreadline6-dev......
...........................
Requirements installation successful.
Installing Ruby from source to: /usr/local/rvm/rubies/ruby-2.3.3, this may take a while depending on your cpu(s)...
ruby-2.3.3 - #downloading ruby-2.3.3, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.7M  100 13.7M    0     0  2954k      0  0:00:04  0:00:04 --:--:-- 3126k
ruby-2.3.3 - #extracting ruby-2.3.3 to /usr/local/rvm/src/ruby-2.3.3....
ruby-2.3.3 - #configuring............................................................
ruby-2.3.3 - #post-configuration..
ruby-2.3.3 - #compiling................................................................................
ruby-2.3.3 - #installing...............
ruby-2.3.3 - #making binaries executable..
ruby-2.3.3 - #downloading rubygems-2.6.11
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  748k  100  748k    0     0   259k      0  0:00:02  0:00:02 --:--:--  259k
No checksum for downloaded archive, recording checksum in user configuration.
ruby-2.3.3 - #extracting rubygems-2.6.11....
ruby-2.3.3 - #removing old rubygems.........
$LANG was empty, setting up LANG=C, if it fails again try setting LANG to something sane and try again.
ruby-2.3.3 - #installing rubygems-2.6.11......................
ruby-2.3.3 - #gemset created /usr/local/rvm/gems/ruby-2.3.3@global
ruby-2.3.3 - #importing gemset /usr/local/rvm/gemsets/global.gems...............................................
ruby-2.3.3 - #generating global wrappers........
ruby-2.3.3 - #gemset created /usr/local/rvm/gems/ruby-2.3.3
ruby-2.3.3 - #importing gemsetfile /usr/local/rvm/gemsets/default.gems evaluated to empty gem list
ruby-2.3.3 - #generating default wrappers........
ruby-2.3.3 - #adjusting #shebangs for (gem irb erb ri rdoc testrb rake).
Install of ruby-2.3.3 - #complete
Ruby was built without documentation, to build it run: rvm docs generate-ri
```


Are your packages out of date?

**Comment by coldnebo** [comment]
Not according to apt-get update/upgrade, but we have an internal mirror and manage our own build... so it could be out of date. It's certainly not 8.7.  Are you using stable?

**Comment by coldnebo** [comment]
I think this is a problem with our build of 8.3.

**Comment by jrgifford** [comment]
OK! If you decide that it isn't, feel free to reopen this and I'll dig in some more. I only spent a few moments on this over lunch.

**Comment by coldnebo** [comment]
So on further review with people at work, someone asked why Ruby isn't doing an autoconf test for SYS_random instead of assuming it can be called if it is defined, which seems like a bug.  They also mentioned fallback to /dev/urandom if the autoconf rule was testing properly.  This might be a Ruby 2.3.3 issue since rvm is just unpacking the source, no?

**Comment by pkuczynski** [comment]
As you correctly pointed out, we are not responsible for developing Ruby. All RVM does is compile Ruby from source or install from binary when possible. For the first case, it also installs dependencies. Feel free to drop a bug report in Ruby repo https://github.com/ruby/ruby

**Comment by coldnebo** [comment]
yep, will do.

**Comment by mpapis** [comment]
I might add that when ruby fixes it we can add a patch to address it in older rubies.

**Comment by coldnebo** [comment]
Just as a postscript for people who stumble into this same issue, I was able to work around it by doing this:

    rvm install 2.3.3 --disable-binary --patch /tmp/rubyvm.patch

rubyvm.patch: https://gist.github.com/coldnebo/98d6166feb4c16220afe451a012c98a0

**Comment by mpapis** [comment]
@coldnebo did you open a ticket for ruby with the fix?

**Comment by coldnebo** [comment]
Ah, looks like someone (Eric Wong) beat me to it (4 months ago!), even submitted the same patch!

* https://bugs.ruby-lang.org/issues/13103

**Comment by mpapis** [comment]
so this patch is approved by ruby and we should just backport it?

**Comment by coldnebo** [comment]
I may not be the one to ask, but it looks like the issue is still 'open', so maybe needs to go through a round of acceptance testing before final approval and close?  It seems harmless enough. How 'aggressive' is rvm in applying patches for these kinds of issues?  :)

**Comment by pkuczynski** [comment]
@coldnebo would that patch be required for any platform or only for specific linux versions? I am keen to add it, but not sure if it would not break anything on mac OS, Windows or other platforms?

**Comment by pkuczynski** [comment]
@coldnebo I prepared a branch including the patch you have provided. Would you be so keen and test it for me?

```
rvm get branch /bugfix/4000-randomc-patch
rvm remove 2.3.3
rvm install 2.3.3 --disable-binary
```

**Comment by coldnebo** [comment]
@pkuczynski the ruby source supports multiple platforms, but the patch only affects random.c for linux systems.  Note the line: `+#elif defined __linux__ && defined __NR_getrandom`

The source should still compile for all supported platforms.

**Comment by coldnebo** [comment]
@pkuczynski sure, give me a few...

**Comment by coldnebo** [comment]
confirmed it works!
(ignore that I'm root, this is for a multiuser install)

```
# rvm get branch /bugfix/4000-randomc-patch
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
Verifying /DONOTDELETE/shared/rvm/archives/rvm-installer.asc
gpg: Signature made Mon 20 Feb 2017 09:05:42 AM EST using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [unknown]
gpg:                 aka "Michal Papis <michal.papis@toptal.com>" [unknown]
gpg:                 aka "[jpeg image of size 5015]" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/DONOTDELETE/shared/rvm/archives/rvm-installer'
Downloading https://github.com/rvm/rvm/archive/bugfix/4000-randomc-patch.tar.gz

Upgrading the RVM installation in /DONOTDELETE/shared/rvm/
Upgrade of RVM in /DONOTDELETE/shared/rvm/ is complete.

# lkyrala,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: https://rvm.io/help and https://twitter.com/rvm_io

Upgrade Notes:

  * No new notes to display.

RVM reloaded!
# rvm remove 2.3.3
ruby-2.3.3 - #removing src/ruby-2.3.3..
ruby-2.3.3 - #removing rubies/ruby-2.3.3..
ruby-2.3.3 - #removing gems.............
ruby-2.3.3 - #removing aliases
ruby-2.3.3 - #removing wrappers..............
ruby-2.3.3 - #removing environments..............
Now using system ruby.
# rvm install 2.3.3 --disable-binary
Checking requirements for debian.
Requirements installation successful.
Installing Ruby from source to: /DONOTDELETE/shared/rvm/rubies/ruby-2.3.3, this may take a while depending on your cpu(s)...
ruby-2.3.3 - #downloading ruby-2.3.3, this may take a while depending on your connection...
ruby-2.3.3 - #extracting ruby-2.3.3 to /DONOTDELETE/shared/rvm/src/ruby-2.3.3....
ruby-2.3.3 - #applying patch /DONOTDELETE/shared/rvm/patches/ruby/2.3.3/random_c_using_NR_prefix.patch.
ruby-2.3.3 - #configuring..........................................................
ruby-2.3.3 - #post-configuration..
ruby-2.3.3 - #compiling.................................................................................
ruby-2.3.3 - #installing..............
ruby-2.3.3 - #making binaries executable..
ruby-2.3.3 - #downloading rubygems-2.6.12
ruby-2.3.3 - #extracting rubygems-2.6.12.....
ruby-2.3.3 - #removing old rubygems.........
ruby-2.3.3 - #installing rubygems-2.6.12.........................
ruby-2.3.3 - #gemset created /DONOTDELETE/shared/rvm/gems/ruby-2.3.3@global
ruby-2.3.3 - #importing gemset /DONOTDELETE/shared/rvm/gemsets/global.gems...............................................
ruby-2.3.3 - #generating global wrappers........
ruby-2.3.3 - #gemset created /DONOTDELETE/shared/rvm/gems/ruby-2.3.3
ruby-2.3.3 - #importing gemsetfile /DONOTDELETE/shared/rvm/gemsets/default.gems evaluated to empty gem list
ruby-2.3.3 - #generating default wrappers........
ruby-2.3.3 - #adjusting #shebangs for (gem irb erb ri rdoc testrb rake).
Install of ruby-2.3.3 - #complete 
Please be aware that you just installed a ruby that requires 1 patches just to be compiled on an up to date linux system.
This may have known and unaccounted for security vulnerabilities.
Please consider upgrading to ruby-2.4.1 which will have all of the latest security patches.
Ruby was built without documentation, to build it run: rvm docs generate-ri

```
