### ISSUE TITLE
Patch Ruby 2.0.0 to compile against openssl 1.1.0

### ISSUE THREAD

**Issue by conathan** [rvm/rvm#5165]
## Description

Attempting to install ruby 1.8.7 does not work on OSX brew w/ openssl 1.1.x or Ubuntu w/ openssl 1.1.x.

## Steps to reproduce

(Linux)
<pre>
# Disable attempting to install libssl1.0-dev on ubuntu, requirements_ubuntu_define_libssl function  (ubuntu 20.04 does not have libssl1.0-dev, and we want this against openssl 1.1.x anyway)
sed -i 's@__rvm_version_compare \${_system_version} -ge 17.10@false@' /usr/local/rvm/scripts/functions/requirements/ubuntu

rvm install ruby-2.0.0-p648 --rubygems 2.7.9
</pre>

(OSX)
<pre>
LDFLAGS="-L/usr/local/opt/openssl@1.1/lib" \
CPPFLAGS="-I/usr/local/opt/openssl@1.1/include -Wno-implicit-function-declaration" \
PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig" \
rvm install ruby-2.0.0-p648 --rubygems 2.7.9
</pre>

## Expected behavior

Install of ruby-2.0.0-p648 - #complete 

## Actual behavior

Error running '__rvm_make -j1',
please read /usr/local/rvm/log/1638493265_ruby-2.0.0-p648/make.log

(Multiple errors, openssl based, expected, posting one example)
ossl_digest.c:90:38: error: ‘EVP_MD_CTX_destroy’ undeclared (first use in this function); did you mean ‘EVP_MD_CTX_reset’?

## Environment info

root@xubuntu2004:~# rvm info

ruby-3.0.0:

  system:
    uname:        "Linux xubuntu2004 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Ubuntu"
    version:      "20.04"
    architecture: "x86_64"
    bash:         "/usr/bin/bash => GNU bash, version 5.0.16(1)-release (x86_64-pc-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "ubuntu/20.04/x86_64"

  rvm:
    version:      "1.29.12 (latest)"
    updated:      "1 hour 3 minutes 58 seconds ago"
    path:         "/usr/local/rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "3.0.0p0"
    date:         "2020-12-25"
    platform:     "x86_64-linux"
    patchlevel:   "2020-12-25 revision 95aff21468"
    full_version: "ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]"

  homes:
    gem:          "/usr/local/rvm/gems/ruby-3.0.0"
    ruby:         "/usr/local/rvm/rubies/ruby-3.0.0"

  binaries:
    ruby:         "/usr/local/rvm/rubies/ruby-3.0.0/bin/ruby"
    irb:          "/usr/local/rvm/rubies/ruby-3.0.0/bin/irb"
    gem:          "/usr/local/rvm/rubies/ruby-3.0.0/bin/gem"
    rake:         "/usr/local/rvm/rubies/ruby-3.0.0/bin/rake"

  environment:
    PATH:         "/usr/local/rvm/gems/ruby-3.0.0/bin:/usr/local/rvm/gems/ruby-3.0.0@global/bin:/usr/local/rvm/rubies/ruby-3.0.0/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
    GEM_HOME:     "/usr/local/rvm/gems/ruby-3.0.0"
    GEM_PATH:     "/usr/local/rvm/gems/ruby-3.0.0:/usr/local/rvm/gems/ruby-3.0.0@global"
    MY_RUBY_HOME: "/usr/local/rvm/rubies/ruby-3.0.0"
    IRBRC:        "/usr/local/rvm/rubies/ruby-3.0.0/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

## Provided Patch

Attached is a patch (applied via --patches ~/.rvm/patches/ruby-2.0.0-p648-openssl11x-1.patch) that will allow ruby 2.0.0 to compile against openssl 1.1.x.  This is mostly backported from ruby 2.4.0
[ruby-2.0.0-p648-openssl11x-1.patch.txt](https://github.com/rvm/rvm/files/7646023/ruby-2.0.0-p648-openssl11x-1.patch.txt)

**Comment by dellysoul** [comment]
Getting this error too
